# Generated by Django 4.2.4 on 2023-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=500)),
                ('text_descr', models.TextField(blank=True)),
                ('text_osob1', models.TextField(blank=True)),
                ('text_osob2', models.TextField(blank=True)),
                ('text_osob3', models.TextField(blank=True)),
            ],
        ),
    ]
